# Site settings
title:          Max Parisi
description:    Homepage
url:            https://tinkerer9.github.io

# Author
author:
  name:         Max Parisi
  email:        makermax101@gmail.com
  url:          https://maxparisi.me

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  1

# Links to social media
social:
  email: makermax101@gmail.com
  github: https://github.com/tinkerer9
